version: "3.8"
services:
  bullyJarBot:
    image: bananaztech/bully-jar-bot:latest
    container_name: bully-jar-bot-prod
    restart: always
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      